# -----------------------------------------------------------
# Docker Compose File
# • used by PoP!_OS environemnt
# • not used by macOS environment (uses Docker Desketop)
# -----------------------------------------------------------

services:
  # 1. SQL Server 2019
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    hostname: sqlserver2019
    restart: always
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${CDWWORK_DB_PASSWORD}  # from .env
    volumes:
      - sqlserver_data:/var/opt/mssql

  # 2. MinIO (S3 Compatible Storage)
  minio:
    image: quay.io/minio/minio
    container_name: med-insight-minio
    hostname: med-insight-minio
    restart: always
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}      # from .env
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}  # from .env
    volumes:
      # Maps to a folder in your home directory.
      # Ensure this folder exists: mkdir -p ~/minio-data
      - ${HOME}/minio-data:/data
    command: server /data --console-address ":9001"

  # 3. PostgreSQL 16
  postgres:
    image: postgres:16
    container_name: postgres16
    hostname: postgres16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # from .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  sqlserver_data:
  postgres_data: